version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - updates:/app
  backend:
    image: biggaji/tobiajibade_backend:latest
    ports:
      - "43001:43001"
      
volumes:
  updates: