version: "3.9"
services:
  backend:
    image: biggaji/tobiajibade_backend:v1.0.0
    ports:
      - "43001:43001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=$DATABASE_URL
      - MAIL_USER=$MAIL_USER
      - MAIL_PASS=$MAIL_PASS
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - updates:/app
    restart: always
      
volumes:
  updates: